services:
- docker
node_js:
- '8'

install:
  - docker-compose -f docker-compose-dev.yml up --build -d
  - npm install

script:
  - npm test 
  - npm run teste2e

before_deploy:
- git config --local user.name "badrf"
