language: node_js

services:
- docker
node_js:
- '8'

addons:
  sonarcloud:
    organization: "badrf-github" # the key of the org you chose at step #3
    token:
      secure: "$SONAR_TOKEN" # encrypted value of your token

install:
  - docker-compose -f docker-compose-dev.yml up --build -d
  - npm install

script:
  - npm test 
  - npm run teste2e


after_script:
  - sonar-scanner

before_deploy:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASS"
- git config --local user.name "badrf"
- docker build . -t "pierrinator/cdp2018:$TRAVIS_TAG"
- docker tag "pierrinator/cdp2018:$TRAVIS_TAG" "pierrinator/cdp2018:latest"
- docker push pierrinator/cdp2018:$TRAVIS_TAG
- docker push pierrinator/cdp2018:latest

deploy:
  provider: script
  script: bash ./scripts/deploy.sh
  on:
    tags: true
    branches:
      only:
- /v\d+\.\d+/
