version: '3'
services:
  web:
    build: .
    volumes:
       - .:/app/
       - /app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
     image: pierrinator/mymysql:1.0
     container_name: db
     ports:
       - "3306:3306"
     environment:
       - "MYSQL_ROOT_PASSWORD=cdproot"
       - "MYSQL_USER=cdp"
       - "MYSQL_PASSWORD=cdp"
       - "MYSQL_DATABASE=base1"