-- MySQL Script generated by MySQL Workbench
-- mar. 20 nov. 2018 18:15:08 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema base1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema base1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `base1` DEFAULT CHARACTER SET utf8 ;
USE `base1` ;

-- -----------------------------------------------------
-- Table `base1`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base1`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  PRIMARY KEY (`idusers`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `base1`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base1`.`projects` (
  `id` INT NOT NULL,
  `content` TEXT NULL,
  `name` VARCHAR(255) NULL,
  `created` DATETIME NULL,
  `online` INT NULL,
  `type` VARCHAR(255) NULL DEFAULT '',
  `slug` VARCHAR(255) NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_projects_users_idx` (`user_id` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `base1`.`config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base1`.`config` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `value` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
