-- MySQL Script generated by MySQL Workbench
-- jeu. 06 déc. 2018 16:40:57 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward typeering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_type_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema base1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema base1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `base1` DEFAULT CHARACTER SET utf8 ;
USE `base1` ;

-- -----------------------------------------------------
-- Table `base1`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base1`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  PRIMARY KEY (`idusers`))
type = MyISAM;


-- -----------------------------------------------------
-- Table `base1`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base1`.`projects` (
  `id` INT NOT NULL,
  `content` TEXT NULL,
  `name` VARCHAR(255) NULL,
  `created` VARCHAR(255) NULL,
  `online` INT NULL,
  `type` VARCHAR(255) NULL,
  `slug` VARCHAR(255) NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_projects_users_idx` (`user_id` ASC) VISIBLE)
type = MyISAM;


-- -----------------------------------------------------
-- Table `base1`.`config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base1`.`config` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `value` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
type = MyISAM;

-- -----------------------------------------------------
-- Table `base1`.`issues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base1`.`issues` (
  `id` INT NOT NULL,
  `description` VARCHAR(255) NULL,
  `priority` VARCHAR(255) NULL,
  `difficulty` INT NULL,
  `project_id` INT NULL,
  `projects_id` INT NOT NULL,
  `sprint` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_issues_projects1_idx` (`projects_id` ASC) VISIBLE)
type = MyISAM;


-- -----------------------------------------------------
-- Table `base1`.`sprint`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base1`.`sprint` (
  `idsprint` INT NOT NULL,
  `start` VARCHAR(255) NULL,
  `end` VARCHAR(255) NULL,
  `state` VARCHAR(255) NULL,
  `projects_id` INT NOT NULL,
  PRIMARY KEY (`idsprint`),
  INDEX `fk_sprint_projects1_idx` (`projects_id` ASC) VISIBLE,
  CONSTRAINT `fk_sprint_projects1`
    FOREIGN KEY (`projects_id`)
    REFERENCES `base1`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
type = MyISAM;


-- -----------------------------------------------------
-- Table `base1`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base1`.`task` (
  `idtask` INT NOT NULL,
  `description` TEXT NULL,
  `component` VARCHAR(255) NULL,
  `ressource` VARCHAR(255) NULL,
  `us` VARCHAR(255) NULL,
  `dependancy` VARCHAR(255) NULL,
  `state` VARCHAR(255) NULL,
  `dev` INT NULL,
  `jh` FLOAT NULL,
  `sprint_idsprint` INT NOT NULL,
  PRIMARY KEY (`idtask`),
  INDEX `fk_task_sprint1_idx` (`sprint_idsprint` ASC) VISIBLE,
  CONSTRAINT `fk_task_sprint1`
    FOREIGN KEY (`sprint_idsprint`)
    REFERENCES `base1`.`sprint` (`idsprint`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
type = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
